### ISSUE TITLE
Supplied gridstore.h doesn't work with SE 4.0

### ISSUE THREAD

**Issue by Imisrael** [griddb/go_client#2]
This is the runtime error I've received:

```
put container failed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x4be0c3]

```
Copying SE 4.0's gridstore.h results in the folowing build time errors:

```
g++ -fPIC -std=c++0x -g -O2 -c -o src/TimeSeriesProperties.o -Iinclude -Isrc src/TimeSeriesProperties.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/ContainerInfo.o -Iinclude -Isrc src/ContainerInfo.cpp
src/ContainerInfo.cpp: In member function ‘void griddb::ContainerInfo::init(const GSChar*, GSContainerType, const GSColumnInfo*, int, bool, griddb::ExpirationInfo*)’:
src/ContainerInfo.cpp:89:18: warning: narrowing conversion of ‘propsCount’ from ‘int’ to ‘size_t {aka long unsigned int}’ inside { } [-Wnarrowing]
   mContainerInfo = {containerName, type, propsCount, columnInfoList, rowKeyAssigned};
                  ^
g++ -fPIC -std=c++0x -g -O2 -c -o src/AggregationResult.o -Iinclude -Isrc src/AggregationResult.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/Container.o -Iinclude -Isrc src/Container.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/Store.o -Iinclude -Isrc src/Store.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/StoreFactory.o -Iinclude -Isrc src/StoreFactory.cpp
In file included from src/StoreFactory.cpp:17:0:
src/StoreFactory.h:44:56: warning: converting to non-pointer type ‘int32_t {aka int}’ from NULL [-Wconversion-null]
   Store* get_store(const char* host=NULL, int32_t port=NULL, const char* cluster_name=NULL,
                                                        ^
g++ -fPIC -std=c++0x -g -O2 -c -o src/PartitionController.o -Iinclude -Isrc src/PartitionController.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/Query.o -Iinclude -Isrc src/Query.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/Row.o -Iinclude -Isrc src/Row.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/QueryAnalysisEntry.o -Iinclude -Isrc src/QueryAnalysisEntry.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/RowKeyPredicate.o -Iinclude -Isrc src/RowKeyPredicate.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/RowSet.o -Iinclude -Isrc src/RowSet.cpp
g++ -fPIC -std=c++0x -g -O2 -c -o src/TimestampUtils.o -Iinclude -Isrc src/TimestampUtils.cpp
mkdir -p src/github.com/griddb
ln -s `pwd`/src `pwd`/src/github.com/griddb/go_client
swig -DSWIGWORDSIZE64 -outdir src/github.com/griddb/go_client/ -o src/griddb_go.cxx -c++ -go -cgo -use-shlib -intgosize 64 src/griddb.i
src/Row.h:29: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
src/RowSet.h:57: Warning 314: 'type' is a Go keyword, renaming to 'Xtype'
src/StoreFactory.h:46: Warning 516: Overloaded method griddb::StoreFactory::get_store(char const *,int32_t,char const *,char const *,char const *,char const *,char const *,char const *) ignored,
src/StoreFactory.h:46: Warning 516: using griddb::StoreFactory::get_store(char const *) instead.
sed -i "/^import \"C\"/i// #cgo CXXFLAGS: -std=c++0x -I$\{SRCDIR\}/../include\n// #cgo LDFLAGS: -L$\{SRCDIR\}/../libs -lrt -lgridstore" src/griddb_go.go
g++ -fPIC -std=c++0x -g -O2 -Iinclude -Isrc -c -o src/griddb_go.o -lstdc++ src/griddb_go.cxx
In file included from src/griddb_go.cxx:289:0:
src/StoreFactory.h:44:56: warning: converting to non-pointer type ‘int32_t {aka int}’ from NULL [-Wconversion-null]
   Store* get_store(const char* host=NULL, int32_t port=NULL, const char* cluster_name=NULL,
                                                        ^
src/griddb_go.cxx: In function ‘griddb::ContainerInfo* _wrap_new_ContainerInfo__SWIG_1_griddb_go_7cb2f2a7ebb363dc(_gostring_, _goslice_, intgo, bool, griddb::ExpirationInfo*)’:
src/griddb_go.cxx:1487:41: error: ‘struct swig_stringintint’ has no member named ‘options’
     arg2[i].options = (int32_t) map2[i].options;
                                         ^
src/griddb_go.cxx: In function ‘griddb::ContainerInfo* _wrap_new_ContainerInfo__SWIG_2_griddb_go_7cb2f2a7ebb363dc(_gostring_, _goslice_, intgo, bool)’:
src/griddb_go.cxx:1552:41: error: ‘struct swig_stringintint’ has no member named ‘options’
     arg2[i].options = (int32_t) map2[i].options;
                                         ^
src/griddb_go.cxx: In function ‘griddb::ContainerInfo* _wrap_new_ContainerInfo__SWIG_3_griddb_go_7cb2f2a7ebb363dc(_gostring_, _goslice_, intgo)’:
src/griddb_go.cxx:1615:41: error: ‘struct swig_stringintint’ has no member named ‘options’
     arg2[i].options = (int32_t) map2[i].options;
                                         ^
src/griddb_go.cxx: In function ‘griddb::ContainerInfo* _wrap_new_ContainerInfo__SWIG_4_griddb_go_7cb2f2a7ebb363dc(_gostring_, _goslice_)’:
src/griddb_go.cxx:1676:41: error: ‘struct swig_stringintint’ has no member named ‘options’
     arg2[i].options = (int32_t) map2[i].options;
                                         ^
src/griddb_go.cxx: In function ‘_goslice_ _wrap_ContainerInfo_getColumnInfoList_griddb_go_7cb2f2a7ebb363dc(griddb::ContainerInfo*)’:
src/griddb_go.cxx:1937:22: error: ‘struct swig_stringintint’ has no member named ‘options’
     tmpColumnList[i].options      = (&result)->columnInfo[i].options;
                      ^
src/griddb_go.cxx: In function ‘griddb::Store* _wrap_StoreFactory_getStore__SWIG_7_griddb_go_7cb2f2a7ebb363dc(griddb::StoreFactory*, _gostring_)’:
src/griddb_go.cxx:5199:67: warning: converting to non-pointer type ‘int32_t {aka int}’ from NULL [-Wconversion-null]
     result = (griddb::Store *)(arg1)->get_store((char const *)arg2);
                                                                   ^
src/griddb_go.cxx: In function ‘griddb::Store* _wrap_StoreFactory_getStore__SWIG_8_griddb_go_7cb2f2a7ebb363dc(griddb::StoreFactory*)’:
src/griddb_go.cxx:5219:49: warning: converting to non-pointer type ‘int32_t {aka int}’ from NULL [-Wconversion-null]
     result = (griddb::Store *)(arg1)->get_store();
                                                 ^
make: *** [src/griddb_go.o] Error 1
```

**Comment by knonomura** [comment]
I'm sorry, but the current Go Client is only for GridDB V3.0CE.
Could you please use GridDB V3.0CE ?

**Comment by knonomura** [comment]
I fixed build with GridDB V4.0SE.
Please replace include/gridstore.h into that in GridDB SE and try to build Go Client.

**Comment by Imisrael** [comment]
Hi Nonomura-san,

Thank you for your quick action! New build works perfectly.

Sincerely,
Israel
